name: Build, Package, and Push to Feed

on:
  push:
    branches: [ "master" ]

env: 
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/dynamicscrm/Solutions/_packaging/Solutions-SmartPlacesAndEnergy/nuget/v3/index.json    
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  WORKING_DIRECTORY: OntologyMapper
  DOTNET_VERSION: '6.x' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }} 

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    # Run dotnet build
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --no-restore

    # Run dotnet test
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build --verbosity normal

    # Run dotnet package
    - name: dotnet pack
      run: |
        dotnet pack "${{ env.WORKING_DIRECTORY }}" -c '${{ env.BUILD_CONFIGURATION }}' --version-suffix $GITHUB_RUN_ID

    # Publish the package to Azure Artifacts
    - name: 'dotnet publish'
      run: dotnet nuget push --api-key AzureArtifacts OntologyMapper/src/bin/Release/*.nupkg