name: Pull Request Build

on:
  pull_request:
    branches: [ "main" ]

env: 
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '6.x' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: 
           dotnet restore OntologyMapper
           dotnet restore OntologyMapper.Mapped
    - name: Build
      run: 
           dotnet build OntologyMapper --no-restore
           dotnet build OntologyMapper.Mapped --no-restore
    - name: Test
      run: 
           dotnet test OntologyMapper --no-build --verbosity normal
           dotnet test OntologyMapper.Mapped --no-build --verbosity normal
